apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/alesandrei54321/go-simple-webserver@sha256:0aac76e4d9c1e9fcdd475211c61fb4ed6c15629807e1b2365c89be71b82d5b7f
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
